### ISSUE TITLE
Non CUDA error? 

### ISSUE THREAD

**Issue by enzyme69** [ThereforeGames/txt2mask#18]
I am using Mac M1 machine, probably non CUDA, and getting error when using txt2mask script:
```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Time taken: 1m 18.08s
```

**Comment by BaptisteGarcin** [comment]
same, running on M1 Mac

**Comment by theesfeld** [comment]
line 124 in txt2mask.py:

`model.load_state_dict(torch.load(d64_file, map_location=torch.device('cuda')), strict=False);`

change `cuda` to `cpu`

**Comment by ride5k** [comment]
> line 124 in txt2mask.py:
> 
> `model.load_state_dict(torch.load(d64_file, map_location=torch.device('cuda')), strict=False);`
> 
> change `cuda` to `cpu`

this worked for me too... kudos!
